// Eamcet predictor
#include <stdio.h>
#include<ctype.h>
int main() {
long int rank;
int caste,gender;
printf("\nenter your eamcet rank=");
scanf("%ld",&rank);
printf("\nenter caste\n1)OC\n2)BC-A\n3)BC-B\n4)BC-C\n5)BC-D\n6)BC-E\n7)SC\n8)ST\n=");
scanf(" %d",&caste);
switch (caste)
{
  case 1: 
          printf("\nFor gender press \n1)1 for male\n2)2 for female\n=");
           scanf("%d",&gender);
        if(gender==1)
          {
            if(rank>0&&rank<=97759)
              {
                  printf("eligible to get seat in vnr\n");
                  printf("Branches\n");
                  if(rank<=36504)
                  printf("CIVIL\n");
                  if(rank<=10093)
                  printf("EEE\n");
                  if(rank<=24704)
                  printf("ME\n");
                  if(rank<=9115)
                  printf("ECE\n");
                  if(rank<=2690)
                  printf("CSE\n");
                  if(rank<=32103)
                  printf("EIE\n");
                  if(rank<=6309)
                  printf("IT\n");
                  if(rank<=97759)
                  printf("AUT\n");
                  if(rank<=6006)
                  printf("CSB\n");
                  if(rank<=4502)
                  printf("CYS\n");
                  if(rank<=3395)
                  printf("CSM\n");
                  if(rank<=3896)
                  printf("CSD\n");
                  if(rank<=5011)
                  printf("CSO\n");
                  if(rank<=4609)
                  printf("AID\n");
                  break;
                 }
                 else
                 {
                 printf("Not eligible for seat in vnr vjiet\n");
                 break;
                 }
          } 
          else
          {
            if(rank>0&&rank<=24704)
                {
                  printf("eligible to get seat in vnr\n");
                  printf("Branches\n");
                  if(rank<=36504)
                  printf("CIVIL\n");
                  if(rank<=16092)
                  printf("EEE\n");
                  if(rank<=26870)
                  printf("ME\n");
                  if(rank<=9513)
                  printf("ECE\n");
                  if(rank<=3093)
                  printf("CSE\n");
                  if(rank<=39152)
                  printf("EIE\n");
                  if(rank<=6647)
                  printf("IT\n");
                  if(rank<=63714)
                  printf("AUT\n");
                  if(rank<=6369)
                  printf("CSB\n");
                  if(rank<=5092)
                  printf("CYS\n");
                  if(rank<=3396)
                  printf("CSM\n");
                  if(rank<=4750)
                  printf("CSD\n");
                  if(rank<=5616)
                  printf("CSO\n");
                  if(rank<=4347)
                  printf("AID\n");
                  break;
                }
            else
            {
                printf("Not eligible for vnr vjiet\n");
                break;
            }
          }
  case 2: 
          printf("\nfor gender press \n1)1 for male\n2)2 for female\n=");
           scanf("%d",&gender);
        if(gender==1)
          {
            if(rank>0&&rank<=70404)
              {
                  printf("eligible to get seat in vnr\n");
                  printf("Branches\n");
                  if(rank<=70404)
                  printf("CIVIL\n");
                  if(rank<=58462)
                  printf("EEE\n");
                  if(rank<=62649)
                  printf("ME\n");
                  if(rank<=29522)
                  printf("ECE\n");
                  if(rank<=6104)
                  printf("CSE\n");
                  if(rank<=58537)
                  printf("EIE\n");
                  if(rank<=14842)
                  printf("IT\n");
                  if(rank<=22497)
                  printf("AUT\n");
                  if(rank<=14600)
                  printf("CSB\n");
                  if(rank<=6909)
                  printf("CYS\n");
                  if(rank<=6119)
                  printf("CSM\n");
                  if(rank<=8002)
                  printf("CSD\n");
                  if(rank<=18033)
                  printf("CSO\n");
                  if(rank<=10175)
                  printf("AID\n");
                  break;
                 }
                 else
                 {
                 printf("Not eligible for seat in vnr vjiet\n");
                 break;
                 }
          } 
          else
          {
            if(rank>0&&rank<=118711)
                {
                  printf("eligible to get seat in vnr\n");
                  printf("Branches\n");
                  if(rank<=87993)
                  printf("CIVIL\n");
                  if(rank<=67751)
                  printf("EEE\n");
                  if(rank<=118711)
                  printf("ME\n");
                  if(rank<=16306)
                  printf("ECE\n");
                  if(rank<=9225)
                  printf("CSE\n");
                  if(rank<=104517)
                  printf("EIE\n");
                  if(rank<=13586)
                  printf("IT\n");
                  if(rank<=63714)
                  printf("AUT\n");
                  if(rank<=11153)
                  printf("CSB\n");
                  if(rank<=14107)
                  printf("CYS\n");
                  if(rank<=8826)
                  printf("CSM\n");
                  if(rank<=10580)
                  printf("CSD\n");
                  if(rank<=13106)
                  printf("CSO\n");
                  if(rank<=12678)
                  printf("AID\n");
                  break;
                }
            else
            {
                printf("Not eligible for vnr vjiet\n");
                break;
            }              

            } 
  case 3: 
          printf("\nfor gender press \n1)1 for male\n2)2 for female\n=");
           scanf("%d",&gender);
        if(gender==1)
          {
            if(rank>0&&rank<=103239)
              {
                  printf("eligible to get seat in vnr\n");
                  printf("Branches\n");
                  if(rank<=103239)
                  printf("CIVIL\n");
                  if(rank<=91613)
                  printf("EEE\n");
                  if(rank<=89199)
                  printf("ME\n");
                  if(rank<=19720)
                  printf("ECE\n");
                  if(rank<=4217)
                  printf("CSE\n");
                  if(rank<=102098)
                  printf("EIE\n");
                  if(rank<=11251)
                  printf("IT\n");
                  if(rank<=78465)
                  printf("AUT\n");
                  if(rank<=9384)
                  printf("CSB\n");
                  if(rank<=9068)
                  printf("CYS\n");
                  if(rank<=5208)
                  printf("CSM\n");
                  if(rank<=7202)
                  printf("CSD\n");
                  if(rank<=10461)
                  printf("CSO\n");
                  if(rank<=6077)
                  printf("AID\n");
                  break;
                 }
                 else
                 {
                 printf("Not eligible for seat in vnr vjiet\n");
                 break;
                 }
          } 
          else
          {
            if(rank>0&&rank<=121212)
                {
                  printf("eligible to get seat in vnr\n");
                  printf("Branches\n");
                  if(rank<=103000)
                  printf("CIVIL\n");
                  if(rank<=92166)
                  printf("EEE\n");
                  if(rank<=121212)
                  printf("ME\n");
                  if(rank<=17518)
                  printf("ECE\n");
                  if(rank<=4465)
                  printf("CSE\n");
                  if(rank<=84183)
                  printf("EIE\n");
                  if(rank<=11657)
                  printf("IT\n");
                  if(rank<=63714)
                  printf("AUT\n");
                  if(rank<=9230)
                  printf("CSB\n");
                  if(rank<=8602)
                  printf("CYS\n");
                  if(rank<=6891)
                  printf("CSM\n");
                  if(rank<=7714)
                  printf("CSD\n");
                  if(rank<=11261)
                  printf("CSO\n");
                  if(rank<=6711)
                  printf("AID\n");
                  break;
                }
            else
            {
                printf("Not eligible for vnr vjiet\n");
                break;
            }
  case 4: 
          printf("\nfor gender press \n1)1 for male\n2)2 for female\n=");
           scanf("%d",&gender);
        if(gender==1)
          {
            if(rank>0&&rank<=81496)
              {
                  printf("eligible to get seat in vnr\n");
                  printf("Branches\n");
                  if(rank<=51848)
                  printf("CIVIL\n");
                  if(rank<=10093)
                  printf("EEE\n");
                  if(rank<=81496)
                  printf("ME\n");
                  if(rank<=25069)
                  printf("ECE\n");
                  if(rank<=5336)
                  printf("CSE\n");
                  if(rank<=26662)
                  printf("EIE\n");
                  if(rank<=17226)
                  printf("IT\n");
                  if(rank<=32117)
                  printf("AUT\n");
                  if(rank<=6006)
                  printf("CSB\n");
                  if(rank<=4502)
                  printf("CYS\n");
                  if(rank<=5414)
                  printf("CSM\n");
                  if(rank<=8820)
                  printf("CSD\n");
                  if(rank<=5011)
                  printf("CSO\n");
                  if(rank<=4609)
                  printf("AID\n");
                  break;
                 }
                 else
                 {
                 printf("Not eligible for seat in vnr vjiet\n");
                 break;
                 }
          } 
          else
          {
            if(rank>0&&rank<=36504)
                {
                  printf("eligible to get seat in vnr\n");
                  printf("Branches\n");
                  if(rank<=36504)
                  printf("CIVIL\n");
                  if(rank<=16092)
                  printf("EEE\n");
                  if(rank<=26870)
                  printf("ME\n");
                  if(rank<=24580)
                  printf("ECE\n");
                  if(rank<=3093)
                  printf("CSE\n");
                  if(rank<=39152)
                  printf("EIE\n");
                  if(rank<=14694)
                  printf("IT\n");
                  if(rank<=63714)
                  printf("AUT\n");
                  if(rank<=6369)
                  printf("CSB\n");
                  if(rank<=12274)
                  printf("CYS\n");
                  if(rank<=3396)
                  printf("CSM\n");
                  if(rank<=4750)
                  printf("CSD\n");
                  if(rank<=5616)
                  printf("CSO\n");
                  if(rank<=4347)
                  printf("AID\n");
                  break;
                }
            else
            {
                printf("Not eligible for vnr vjiet\n");
                break;
            }
  case 5: 
          printf("\nfor gender press \n1)1 for male\n2)2 for female\n=");
           scanf("%d",&gender);
        if(gender==1)
          {
            if(rank>0&&rank<=106381)
              {
                  printf("eligible to get seat in vnr\n");
                  printf("Branches\n");
                  if(rank<=58098)
                  printf("CIVIL\n");
                  if(rank<=64452)
                  printf("EEE\n");
                  if(rank<=106381)
                  printf("ME\n");
                  if(rank<=18857)
                  printf("ECE\n");
                  if(rank<=3643)
                  printf("CSE\n");
                  if(rank<=48082)
                  printf("EIE\n");
                  if(rank<=9260)
                  printf("IT\n");
                  if(rank<=64678)
                  printf("AUT\n");
                  if(rank<=9298)
                  printf("CSB\n");
                  if(rank<=5801)
                  printf("CYS\n");
                  if(rank<=4440)
                  printf("CSM\n");
                  if(rank<=6615)
                  printf("CSD\n");
                  if(rank<=7461)
                  printf("CSO\n");
                  if(rank<=7326)
                  printf("AID\n");
                  break;
                 }
                 else
                 {
                 printf("Not eligible for seat in vnr vjiet\n");
                 break;
                 }
          } 
          else
          {
            if(rank>0&&rank<=79156)
                {
                  printf("eligible to get seat in vnr\n");
                  printf("Branches\n");
                  if(rank<=72852)
                  printf("CIVIL\n");
                  if(rank<=79156)
                  printf("EEE\n");
                  if(rank<=62876)
                  printf("ME\n");
                  if(rank<=15124)
                  printf("ECE\n");
                  if(rank<=4098)
                  printf("CSE\n");
                  if(rank<=30745)
                  printf("EIE\n");
                  if(rank<=14607)
                  printf("IT\n");
                  if(rank<=63714)
                  printf("AUT\n");
                  if(rank<=6843)
                  printf("CSB\n");
                  if(rank<=12556)
                  printf("CYS\n");
                  if(rank<=6257)
                  printf("CSM\n");
                  if(rank<=5645)
                  printf("CSD\n");
                  if(rank<=11228)
                  printf("CSO\n");
                  if(rank<=10853)
                  printf("AID\n");
                  break;
                }
            else
            {
                printf("Not eligible for vnr vjiet\n");
                break;
            }              

            } 
  case 6: 
          printf("\nfor gender press \n1)1 for male\n2)2 for female\n=");
           scanf("%d",&gender);
        if(gender==1)
          {
            if(rank>0&&rank<=88762)
              {
                  printf("eligible to get seat in vnr\n");
                  printf("Branches\n");
                  if(rank<=88762)
                  printf("CIVIL\n");
                  if(rank<=76109)
                  printf("EEE\n");
                  if(rank<=77436)
                  printf("ME\n");
                  if(rank<=23016)
                  printf("ECE\n");
                  if(rank<=6050)
                  printf("CSE\n");
                  if(rank<=92323)
                  printf("EIE\n");
                  if(rank<=10614)
                  printf("IT\n");
                  if(rank<=51538)
                  printf("AUT\n");
                  if(rank<=15307)
                  printf("CSB\n");
                  if(rank<=10106)
                  printf("CYS\n");
                  if(rank<=7738)
                  printf("CSM\n");
                  if(rank<=9701)
                  printf("CSD\n");
                  if(rank<=12073)
                  printf("CSO\n");
                  if(rank<=11027)
                  printf("AID\n");
                  break;
                 }
                 else
                 {
                 printf("Not eligible for seat in vnr vjiet\n");
                 break;
                 }
          } 
          else
          {
            if(rank>0&&rank<=111557)
                {
                  printf("eligible to get seat in vnr\n");
                  printf("Branches\n");
                  if(rank<=105179)
                  printf("CIVIL\n");
                  if(rank<=50507)
                  printf("EEE\n");
                  if(rank<=57415)
                  printf("ME\n");
                  if(rank<=24278)
                  printf("ECE\n");
                  if(rank<=3442)
                  printf("CSE\n");
                  if(rank<=111557)
                  printf("EIE\n");
                  if(rank<=16325)
                  printf("IT\n");
                  if(rank<=63714)
                  printf("AUT\n");
                  if(rank<=9230)
                  printf("CSB\n");
                  if(rank<=8602)
                  printf("CYS\n");
                  if(rank<=5747)
                  printf("CSM\n");
                  if(rank<=10006)
                  printf("CSD\n");
                  if(rank<=24723)
                  printf("CSO\n");
                  if(rank<=38369)
                  printf("AID\n");
                  break;
                }
            else
            {
                printf("Not eligible for vnr vjiet\n");
                break;
            } 
  case 7: 
          printf("\nfor gender press \n1)1 for male\n2)2 for female\n=");
           scanf("%d",&gender);
        if(gender==1)
          {
            if(rank>0&&rank<=119424)
              {
                  printf("eligible to get seat in vnr\n");
                  printf("Branches\n");
                  if(rank<=97308)
                  printf("CIVIL\n");
                  if(rank<=60478)
                  printf("EEE\n");
                  if(rank<=89700)
                  printf("ME\n");
                  if(rank<=36367)
                  printf("ECE\n");
                  if(rank<=13201)
                  printf("CSE\n");
                  if(rank<=101847)
                  printf("EIE\n");
                  if(rank<=28337)
                  printf("IT\n");
                  if(rank<=119424)
                  printf("AUT\n");
                  if(rank<=32528)
                  printf("CSB\n");
                  if(rank<=27252)
                  printf("CYS\n");
                  if(rank<=17769)
                  printf("CSM\n");
                  if(rank<=19853)
                  printf("CSD\n");
                  if(rank<=32899)
                  printf("CSO\n");
                  if(rank<=19987)
                  printf("AID\n");
                  break;
                 }
                 else
                 {
                 printf("Not eligible for seat in vnr vjiet\n");
                 break;
                 }
          } 
          else
          {
            if(rank>0&&rank<=177586)
                {
                  printf("eligible to get seat in vnr\n");
                  printf("Branches\n");
                  if(rank<=120840)
                  printf("CIVIL\n");
                  if(rank<=70533)
                  printf("EEE\n");
                  if(rank<=117586)
                  printf("ME\n");
                  if(rank<=44085)
                  printf("ECE\n");
                  if(rank<=15845)
                  printf("CSE\n");
                  if(rank<=105610)
                  printf("EIE\n");
                  if(rank<=26690)
                  printf("IT\n");
                  if(rank<=63714)
                  printf("AUT\n");
                  if(rank<=6843)
                  printf("CSB\n");
                  if(rank<=26046)
                  printf("CYS\n");
                  if(rank<=25996)
                  printf("CSM\n");
                  if(rank<=28910)
                  printf("CSD\n");
                  if(rank<=31439)
                  printf("CSO\n");
                  if(rank<=48487)
                  printf("AID\n");
                  break;
                }
            else
            {
                printf("Not eligible for vnr vjiet\n");
                break;
            }              

            } 
  case 8: 
          printf("\nfor gender press \n1)1 for male\n2)2 for female\n=");
           scanf("%d",&gender);
        if(gender==1)
          {
            if(rank>0&&rank<=116903)
              {
                  printf("eligible to get seat in vnr\n");
                  printf("Branches\n");
                  if(rank<=58700)
                  printf("CIVIL\n");
                  if(rank<=49448)
                  printf("EEE\n");
                  if(rank<=94867)
                  printf("ME\n");
                  if(rank<=27957)
                  printf("ECE\n");
                  if(rank<=16097)
                  printf("CSE\n");
                  if(rank<=120577)
                  printf("EIE\n");
                  if(rank<=25078)
                  printf("IT\n");
                  if(rank<=116903)
                  printf("AUT\n");
                  if(rank<=37126)
                  printf("CSB\n");
                  if(rank<=15695)
                  printf("CYS\n");
                  if(rank<=17139)
                  printf("CSM\n");
                  if(rank<=23667)
                  printf("CSD\n");
                  if(rank<=12073)
                  printf("CSO\n");
                  if(rank<=23368)
                  printf("AID\n");
                  break;
                 }
                 else
                 {
                 printf("Not eligible for seat in vnr vjiet\n");
                 break;
                 }
          } 
          else
          {
            if(rank>0&&rank<=120546)
                {
                  printf("eligible to get seat in vnr\n");
                  printf("Branches\n");
                  if(rank<=104403)
                  printf("CIVIL\n");
                  if(rank<=38016)
                  printf("EEE\n");
                  if(rank<=120546)
                  printf("ME\n");
                  if(rank<=37975)
                  printf("ECE\n");
                  if(rank<=15581)
                  printf("CSE\n");
                  if(rank<=117416)
                  printf("EIE\n");
                  if(rank<=38193)
                  printf("IT\n");
                  if(rank<=116941)
                  printf("AUT\n");
                  if(rank<=3307)
                  printf("CSB\n");
                  if(rank<=17997)
                  printf("CYS\n");
                  if(rank<=32153)
                  printf("CSM\n");
                  if(rank<=27566)
                  printf("CSD\n");
                  if(rank<=42746)
                  printf("CSO\n");
                  if(rank<=38369)
                  printf("AID\n");
                  break;
                }
            else
            {
                printf("Not eligible for vnr vjiet\n");
                break;
            }                                 

            }
                  
          }
       }
     }
  }
return 0;
}